# Generated by Django 2.1.3 on 2018-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtcheat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='groupid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
