# Generated by Django 2.1.3 on 2018-12-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtcheat', '0002_userinfo_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
